name: La Vita
favicon: null
layout_spectrum: 0
typography_spectrum: 0.14385
title: 'What it is, What it was, What it shall be'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c6d0d3'
    - '#99a4ac'
    - '#334656'
    - '#221618'
    - '#79312a'
  brandStrength: 0.5
  lightness: 0.9323635324835777
  saturation: 0.125
  rhythmicContrast: 0.8262232088018209
purpose: []
