name: Design Algorithm
favicon: null
layout_spectrum: 0.74263
typography_spectrum: 0.42721
title: "the bits that bots don't bother with"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d0d5d8'
    - '#405160'
    - '#9da7b0'
    - '#231a1b'
    - '#af654c'
  brandStrength: 0.5
  lightness: 1
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
